import type { Metadata, Viewport } from "next";
import { cookies } from "next/headers";
import { SessionProvider } from "next-auth/react";
import { Pridi, Work_Sans } from "next/font/google";
import { ToastProvider } from "@/components/Toast";
import "./globals.css";

// Body / UI typeface. Light + regular + medium + semibold covers every
// weight the app uses today. Italic loaded so the editorial opener
// (.digest-opener) renders true italic rather than synthesized.
const workSans = Work_Sans({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600"],
  style: ["normal", "italic"],
  variable: "--font-work-sans",
  display: "swap",
});

// Display typeface — reserved for digest page titles and the askscout
// wordmark/logo. Loads regular through bold so existing logo weights
// (some at 700) render natively rather than being synthesized.
const pridi = Pridi({
  subsets: ["latin"],
  // 200 (ExtraLight) added for the hero title's mixed-weight
  // treatment per Figma 244:2426: "Your morning" + "in 10 seconds"
  // render at ExtraLight while "code briefing" sits at Regular.
  weight: ["200", "400", "500", "600", "700"],
  variable: "--font-pridi",
  display: "swap",
});

export const metadata: Metadata = {
  // metadataBase is required for Next to absolutize any relative OG
  // image URLs (and silences the build-time warning). It is also
  // the base used by `alternates.canonical` on individual pages
  // when they supply a path-only canonical like "/docs".
  metadataBase: new URL("https://askscout.dev"),
  title: "askScout · Your morning code briefing in 10 seconds",
  description:
    "A daily digest of your code in plain language so you can pick up exactly where you left off. Built for developers using Claude Code, Cursor, and Codex.",
  keywords: [
    "vibe coding",
    "vibe coders",
    "vibe coding digest",
    "ai coding tools",
    "git digest",
    "developer productivity",
    "daily standup",
  ],
  openGraph: {
    title: "askScout · Your morning code briefing in 10 seconds",
    description:
      "A daily digest of your code in plain language so you can pick up exactly where you left off. Built for developers using Claude Code, Cursor, and Codex.",
    url: "https://askscout.dev",
    siteName: "askScout",
    type: "website",
    locale: "en_US",
    images: [
      {
        url: "/og-image.png",
        width: 1200,
        height: 630,
        alt: "askScout · Your morning code briefing in 10 seconds",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "askScout · Your morning code briefing in 10 seconds",
    description:
      "A daily digest of your code in plain language so you can pick up exactly where you left off. Built for developers using Claude Code, Cursor, and Codex.",
    images: ["/og-image.png"],
  },
  // Favicon set generated by realfavicongenerator. Files live in
  // apps/web/public/ and are referenced as absolute paths so they
  // resolve from the site root regardless of which page renders them.
  // favicon.ico is also auto-served by the App Router from the same
  // location, but listing it explicitly here means the <link rel="icon">
  // tag appears in the rendered HTML for tools that scrape head markup.
  icons: {
    icon: [
      { url: "/favicon.ico", sizes: "any" },
      { url: "/favicon-16x16.png", sizes: "16x16", type: "image/png" },
      { url: "/favicon-32x32.png", sizes: "32x32", type: "image/png" },
    ],
    apple: { url: "/apple-touch-icon.png", sizes: "180x180", type: "image/png" },
  },
  manifest: "/site.webmanifest",
};

/* Viewport export is the Next 14+ requirement for mobile-friendly
 * <meta name="viewport"> + <meta name="theme-color">.
 * Docs: https://nextjs.org/docs/app/api-reference/functions/generate-viewport
 *
 * theme-color drives the mobile browser chrome (Chrome's address
 * bar fill on Android, Safari's status bar on iOS PWAs). Set to
 * bg-primary #070707 so the chrome blends seamlessly into the
 * dark-default site. Matches theme_color in site.webmanifest. */
export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  themeColor: "#070707",
};

/* Site-wide Organization + WebSite JSON-LD in a single @graph
 * block so the entity definitions appear on every page without
 * duplicating Organization across the per-page schemas.
 *
 * @graph is schema.org's canonical pattern for combining multiple
 * top-level entities in one JSON-LD payload (used by Yoast SEO,
 * Rank Math, and most professional CMS plugins). Internal @id
 * URLs let other schemas on the page reference these without
 * re-inlining the full Organization object.
 *
 * Refs:
 *   https://schema.org/Organization
 *   https://schema.org/WebSite
 *   https://developers.google.com/search/docs/appearance/structured-data/logo
 */
const SITE_GRAPH = {
  "@context": "https://schema.org",
  "@graph": [
    {
      "@type": "Organization",
      "@id": "https://askscout.dev/#organization",
      name: "askScout",
      url: "https://askscout.dev",
      logo: {
        "@type": "ImageObject",
        url: "https://askscout.dev/logo-white.svg",
      },
      description:
        "Open-source daily digest tool for developers and vibe coders. Reads your git activity and writes a plain-English summary of what you actually shipped.",
      sameAs: ["https://github.com/charleshonig5/askscout"],
    },
    {
      "@type": "WebSite",
      "@id": "https://askscout.dev/#website",
      name: "askScout",
      url: "https://askscout.dev",
      inLanguage: "en",
      publisher: { "@id": "https://askscout.dev/#organization" },
    },
  ],
};

/**
 * Theme is server-rendered via a cookie. The HTML arrives with the
 * correct data-theme attribute already set, so:
 *   - no flash of the wrong theme on first paint
 *   - no inline bootstrap script that can race with hydration
 *   - no localStorage edge cases (private mode, preview-URL
 *     scoping, browser-clears-on-close settings)
 *
 * The toggle (ThemeToggle.tsx) writes the cookie + updates the
 * attribute on the live document. Default: dark, the brand default.
 */
export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const cookieStore = await cookies();
  const stored = cookieStore.get("theme")?.value;
  const theme = stored === "light" || stored === "dark" ? stored : "dark";

  return (
    <html lang="en" data-theme={theme} className={`${workSans.variable} ${pridi.variable}`}>
      <body>
        {/* Site-wide structured data — renders on every page. */}
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(SITE_GRAPH) }}
        />
        {/* ToastProvider sits OUTSIDE SessionProvider so toasts keep
            working even if auth has a transient client-side error. */}
        <ToastProvider>
          <SessionProvider>{children}</SessionProvider>
        </ToastProvider>
      </body>
    </html>
  );
}
