import type { Metadata, Viewport } from "next";
import { cookies } from "next/headers";
import { SessionProvider } from "next-auth/react";
import { Pridi, Work_Sans } from "next/font/google";
import { ToastProvider } from "@/components/Toast";
import "./globals.css";

// Body / UI typeface. Light + regular + medium + semibold covers every
// weight the app uses today. Italic loaded so the editorial opener
// (.digest-opener) renders true italic rather than synthesized.
const workSans = Work_Sans({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600"],
  style: ["normal", "italic"],
  variable: "--font-work-sans",
  display: "swap",
});

// Display typeface — reserved for digest page titles and the askscout
// wordmark/logo. Loads regular through bold so existing logo weights
// (some at 700) render natively rather than being synthesized.
const pridi = Pridi({
  subsets: ["latin"],
  // 200 (ExtraLight) added for the hero title's mixed-weight
  // treatment per Figma 244:2426: "Your morning" + "in 10 seconds"
  // render at ExtraLight while "code briefing" sits at Regular.
  weight: ["200", "400", "500", "600", "700"],
  variable: "--font-pridi",
  display: "swap",
});

export const metadata: Metadata = {
  // metadataBase is required for Next to absolutize any relative OG
  // image URLs (and silences the build-time warning). It is also
  // the base used by `alternates.canonical` on individual pages
  // when they supply a path-only canonical like "/docs".
  metadataBase: new URL("https://askscout.dev"),
  title: "AskScout, the daily digest for vibe coders",
  description:
    "AI wrote half your code this week. AskScout reads your repo and tells you, in plain English, what you actually shipped.",
  keywords: [
    "vibe coding",
    "vibe coders",
    "vibe coding digest",
    "ai coding tools",
    "git digest",
    "developer productivity",
    "daily standup",
  ],
  openGraph: {
    title: "AskScout, the daily digest for vibe coders",
    description:
      "AI wrote half your code this week. AskScout reads your repo and tells you what you actually shipped.",
    url: "https://askscout.dev",
    siteName: "AskScout",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "AskScout, the daily digest for vibe coders",
    description:
      "AI wrote half your code this week. AskScout reads your repo and tells you what you actually shipped.",
  },
  // Favicon set generated by realfavicongenerator. Files live in
  // apps/web/public/ and are referenced as absolute paths so they
  // resolve from the site root regardless of which page renders them.
  // favicon.ico is also auto-served by the App Router from the same
  // location, but listing it explicitly here means the <link rel="icon">
  // tag appears in the rendered HTML for tools that scrape head markup.
  icons: {
    icon: [
      { url: "/favicon.ico", sizes: "any" },
      { url: "/favicon-16x16.png", sizes: "16x16", type: "image/png" },
      { url: "/favicon-32x32.png", sizes: "32x32", type: "image/png" },
    ],
    apple: { url: "/apple-touch-icon.png", sizes: "180x180", type: "image/png" },
  },
  manifest: "/site.webmanifest",
};

/* Viewport export is the Next 14+ requirement for mobile-friendly
 * <meta name="viewport"> + <meta name="theme-color">.
 * Docs: https://nextjs.org/docs/app/api-reference/functions/generate-viewport
 *
 * theme-color drives the mobile browser chrome (Chrome's address
 * bar fill on Android, Safari's status bar on iOS PWAs). Set to
 * bg-primary #070707 so the chrome blends seamlessly into the
 * dark-default site. Matches theme_color in site.webmanifest. */
export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  themeColor: "#070707",
};

/**
 * Theme is server-rendered via a cookie. The HTML arrives with the
 * correct data-theme attribute already set, so:
 *   - no flash of the wrong theme on first paint
 *   - no inline bootstrap script that can race with hydration
 *   - no localStorage edge cases (private mode, preview-URL
 *     scoping, browser-clears-on-close settings)
 *
 * The toggle (ThemeToggle.tsx) writes the cookie + updates the
 * attribute on the live document. Default: dark, the brand default.
 */
export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const cookieStore = await cookies();
  const stored = cookieStore.get("theme")?.value;
  const theme = stored === "light" || stored === "dark" ? stored : "dark";

  return (
    <html lang="en" data-theme={theme} className={`${workSans.variable} ${pridi.variable}`}>
      <body>
        {/* ToastProvider sits OUTSIDE SessionProvider so toasts keep
            working even if auth has a transient client-side error. */}
        <ToastProvider>
          <SessionProvider>{children}</SessionProvider>
        </ToastProvider>
      </body>
    </html>
  );
}
